array_layout = "Block"
closure_block_indent_threshold = 1
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_call_style = "Block"
format_strings = true
generics_indent = "Block"
take_source_hints = false
use_try_shorthand = true
where_style = "Rfc"
write_mode = 'Overwrite'
