[package]
authors = ["Seeker14491 <seeker14491@gmail.com>"]
name = "bbrot-lib"
version = "0.0.1"

[dependencies]
crossbeam = "0.2.10"
image = "0.14.0"
num = "0.1.37"
num_cpus = "1.4.0"
rand = "0.3.15"
